### ISSUE TITLE
关于Demo的问题

### ISSUE THREAD

**Issue by fanweixiao** [fanweixiao/wxapp-socket-io#4]
建议`Demo`项目里添加使用[Socket.IO官方的Chat Demo](http://socket.io/demos/chat/)，因为这种方式下，开发者不需要再去搭建一个本地server，就可以直接测试看到交互效果了。

同时，现在的Demo里，还夹杂了与演示咱们[wxapp-socket-io](https://github.com/fanweixiao/wxapp-socket-io)无关的一些代码，建议都去掉，这样会更简洁明了的讲述咱们项目的使用之方便~

**Comment by gongzili456** [comment]
已完成Demo，使用 socket.io 官网的 server
